### ISSUE TITLE
官网[可视化编辑]开源吗

### ISSUE THREAD

**Issue by Jeesoong** [alibaba/cloud-charts#11]
请教：官网中的可视化编辑-配置项部分 有开源计划没

**Comment by maplor** [comment]
可视化编辑没有太多代码量，编辑表单使用的是 datav 的表单组件（目前没有开源）：https://help.aliyun.com/document_detail/155352.html
将编辑器生成的配置项直接传入了图表。图表组件会自动响应配置项的更新。

**Comment by Jeesoong** [comment]
> 可视化编辑没有太多代码量，编辑表单使用的是 datav 的表单组件（目前没有开源）：https://help.aliyun.com/document_detail/155352.html
> 将编辑器生成的配置项直接传入了图表。图表组件会自动响应配置项的更新。

嗯，感谢指导，这块的思路我了解，只是配置项整理起来有点繁琐。。。

**Comment by maplor** [comment]
> > 可视化编辑没有太多代码量，编辑表单使用的是 datav 的表单组件（目前没有开源）：https://help.aliyun.com/document_detail/155352.html
> > 将编辑器生成的配置项直接传入了图表。图表组件会自动响应配置项的更新。
> 
> 嗯，感谢指导，这块的思路我了解，只是配置项整理起来有点繁琐。。。

配置项在源码中有的，例如：https://github.com/alibaba/cloud-charts/blob/master/src/Wline/gui.schema.json，用的 DataV 表单规范。官网中有配置的组件在代码里都有。
