### ISSUE TITLE
可以单js引用吗

### ISSUE THREAD

**Issue by q1139168548** [alibaba/cloud-charts#17]
只能npm install吗

**Comment by maplor** [comment]
有提供 umd 版本的：
1、可以在 unpkg 或者 jsdeliver 中找到：https://cdn.jsdelivr.net/npm/@alicloud/cloud-charts/
2、npm 下载后在 build 文件夹下是 umd 版本

**Comment by q1139168548** [comment]
感谢回答！

> 有提供 umd 版本的： 1、可以在 unpkg 或者 jsdeliver 中找到：https://cdn.jsdelivr.net/npm/@alicloud/cloud-charts/ 2、npm 下载后在 build 文件夹下是 umd 版本
