### ISSUE TITLE
本地build项目报错

### ISSUE THREAD

**Issue by morance** [alibaba/cloud-charts#3]
期望： 本地build项目正常运行
实际：ReferenceError: primordials is not defined

解决方案: 可以按照[该链接](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node)修复,本质问题gulp版本与node版本要求不一致

**Comment by maplor** [comment]
由于历史原因用了老版本的gulp，在今年的 1.x 大版本会正式去除。0.x 版本我看情况修复一下。

**Comment by maplor** [comment]
1.x 大版本已发布，构建没有问题了。
