### ISSUE TITLE
柱状图，添加柱条颜色渐变功能

### ISSUE THREAD

**Issue by 15700353375** [alibaba/cloud-charts#6]

**Comment by maplor** [comment]
目前是支持的，图表通过 config.colors 可以指定颜色。
而绘图属性和G2一致，可以用这个文档中的方法绘制渐变色 -> https://antv-g2.gitee.io/zh/docs/manual/shape-attrs

例如：

```javascript
const config = {
  colors: ['l(90) 0:#3f90ff 1:#3f90ff00'],
};
```
