### ISSUE TITLE
为啥我npm安装不了

### ISSUE THREAD

**Issue by zhoubo1996** [alibaba/cloud-charts#9]

**Comment by maplor** [comment]
> _No description provided._

是报错还是超时？有详细一些的信息吗？

**Comment by zhoubo1996** [comment]
可以了，时候可以更新兼容vue的啊

**Comment by maplor** [comment]
> 可以了，时候可以更新兼容vue的啊

coming soon 了，本月会发布新的大版本，做好vue版的准备。
